### PR TITLE
Add eager infeasbility, dfs and bfs to symex help file

### PR DESCRIPTION
**Pull request by polgreen**
These search options already exist and are undocumented

### CODE REVIEW

**Comment by polgreen** [comment]
@kroening @peterschrammel @cesaro could this PR have a review please?

**Review by martin-cs — APPROVED** [review]
Yes but also see : https://github.com/diffblue/cbmc/pull/1641#pullrequestreview-98007122

(and when I say "see" I mean, make noise about if you want / care)

**Comment by polgreen** [comment]
Thanks. I was aware that Kareem was working on a better symex, but really i just want these pull requests against symex to be merged into the main repo so i don't have to maintain them and so the work doesn't just disappear. This one is trivial but the following 2 are less so.

Who has write access to symex? Can someone merge this one in? Then I can rebase the others

**Comment by martin-cs** [comment]
@polgreen Despite not being a code owner I have a big "Merge pull request" button hovering temptingly in front of my fingers.  If @peterschrammel @cesaro or @kroening don't say something soon I might get tempted to press it...

**Comment by polgreen** [comment]
Please can someone merge this PR? Please?

**Comment by martin-cs** [comment]
No one objected so I figured no one would mind...

Also, the PR is useful and worth having.

**Pull request merged**
